FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN rm requirements.txt

COPY ./library /app

CMD ["celery", "-A", "library.celery", "worker", "--loglevel=info"]
